<?php


namespace Acl\Providers;


use Illuminate\Support\ServiceProvider;

class InstallModuleProvider extends ServiceProvider
{
    protected $module = 'Acl';

    public function boot(){
        app()->booted(function (){
            $this->booted();
        });
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function booted(){
        $permission = array(
            [
                'name'=>'access_dashboard',
                'display_name'=>'Truy cập admin',
                'description'=>'Cho phép tài khoản truy cập admin',
            ],
            [
                'name'=>'role_index',
                'display_name'=>'Xem vai trò',
                'description'=>'Xem danh sách các vai trò quản trị'
            ],
            [
                'name'=>'role_create',
                'display_name'=>'Thêm vai trò',
                'description'=>'Thêm vai trò quản trị'
            ],
            [
                'name'=>'role_edit',
                'display_name'=>'Sửa vai trò',
                'description'=>'Sửa vai trò quản trị'
            ],
            [
                'name'=>'role_delete',
                'display_name'=>'Xóa vai trò',
                'description'=>'Xóa vai trò quản trị'
            ],
            [
                'name'=>'permission_index',
                'display_name'=>'Xem danh sách quyền',
                'description'=>'Xem danh sách các quyền quản trị'
            ],
        );
    }

}
